### ISSUE TITLE
Incompatible with non-stupid-digest-assets gem

### ISSUE THREAD

**Issue by malively** [camertron/turbo-sprockets-rails4#5]
Our rails 4 app includes the non-stupid-digest-assets gem. I tried including your gem and running `rake assets:precompile` and I get the following stack level too deep error.

```
rake aborted!
SystemStackError: stack level too deep
/home/g/.rvm/gems/ruby-2.4.2-jemalloc@gemini/gems/non-stupid-digest-assets-1.0.8/lib/non-stupid-digest-assets.rb:26:in `compile'
/home/g/.rvm/gems/ruby-2.4.2-jemalloc@gemini/gems/turbo-sprockets-rails4-1.2.5/lib/turbo-sprockets/railtie.rb:10:in `compile_with_parallelism'
/home/g/.rvm/gems/ruby-2.4.2-jemalloc@gemini/gems/non-stupid-digest-assets-1.0.8/lib/non-stupid-digest-assets.rb:26:in `compile'
/home/g/.rvm/gems/ruby-2.4.2-jemalloc@gemini/gems/turbo-sprockets-rails4-1.2.5/lib/turbo-sprockets/railtie.rb:10:in `compile_with_parallelism'
```
Browsing through the non-stupid-digest-assets github there is an issue with a work around to get sprockets-derailleur working with it, https://github.com/alexspeller/non-stupid-digest-assets/issues/25 
I tried doing this work around for turbo-sprockets but it didn't seem to work. It would be great if turbo-sprockets could be compatible with non-stupid-digest-assets. Please let me know if you have any ideas for a work around!

**Comment by camertron** [comment]
Hey @malively thanks for the bug report. It would be super helpful if you could put together a demo rails app that reproduces the issue that I could use to dig into the problem. Is that something you'd be willing to do?
